### ISSUE TITLE
Cannot upload a local file into Colab

### ISSUE THREAD

**Issue by jonfernandes** [dxc-technology/DXC-Industrialized-AI-Starter#56] opened 2020-07-22 15:34 UTC
Problem:
In the DXC_Industrialized_AI_Starter.ipynb notebook, there are a couple instances where it suggests you can upload a local file to colab. This doesn't work. The error message I get is : 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

**Comment by npulagam** [comment] 2020-07-22 16:53
Hi @jonfernandes,

Below are the causes and solutions for this issue. 

1. It sounds like third-party cookies may be disabled in your browser. Please enable third-party cookies in your browser (The setting is under chrome://settings/content/cookies).

2. A typical cause of the error you observe is using an unsupported browser or a browser extension. Try disabling extensions. Or, if you are using a browser other than Firefox, Safari, or Chrome, try one of these. 

Please try to do the above steps. 

If you are still facing the issues please let me know.

**Comment by npulagam** [comment] 2020-07-24 14:03
Hi @jonfernandes ,

I belive that you are able to upload the local file into colab notebook,  so closing this issue. If you are still facing any issue in uploading a local files to colab then please reopen this issue or create a new issue.

**Closed by npulagam** 2020-07-24 14:03 UTC
Labels: help wanted
